/**
 * The S3 waivability fixture (spec 007 AC-5-6), as test harness.
 *
 * `__fixtures__/s3-waivability/` is a copy of the VDD run's shared fixture
 * (`.erpaval/vdd/s3-waivability/fixture/`): one base document, the op streams each case applies
 * to it, and the `<case>.stored.json` documents base 0fca043's `apply` WROTE from those streams.
 * The stored documents are the legacy channel — what an older build accepted — so they must
 * never be regenerated by the build under test. `hand-*.json` are hand-edited documents (the
 * channel no fence runs on, trust boundary TB3).
 *
 * Every `check` here runs with the gaming harness's orthogonal embedder over the fixture's two
 * near pairs, never the stub: `SYMSPEC_EMBED_STUB=1` demotes every run `run-weakened` (AC-3-5)
 * and would hide whether a waiver moved `verified`. `testing/` may not name `app/` or
 * `adapters/` (`package-boundary.test.ts`), so the real `check` and solver are INJECTED by the
 * test file, as the gaming shards do.
 */

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { Effect, Layer, ManagedRuntime, Schema } from 'effect'
import { requirementsContentHash } from '../domain/requirements/content-hash.ts'
import { RequirementsDocument } from '../domain/requirements/document.ts'
import { type DocumentOp, decodeOp } from '../domain/requirements/ops.ts'
import { DocPath, DocStore, documentOnlyStore, makeDocPath } from '../ports/doc-store.ts'
import { type EmbedderService, embedderLayerOf } from '../ports/embedder.ts'
import { ErrDocNotFound } from '../ports/errors.ts'
import type { SolverService } from '../ports/solver.ts'
import { orthogonalEmbedder } from './gaming.ts'

const DIR = new URL('./__fixtures__/s3-waivability/', import.meta.url)

/** The absolute path of one fixture file. */
export const fixturePath = (name: string): string => fileURLToPath(new URL(name, DIR))

/** One fixture file's text. */
export const fixtureText = (name: string): string => readFileSync(fixturePath(name), 'utf8')

const decodeDoc = Schema.decodeUnknownSync(RequirementsDocument)

/** A stored fixture document (`base.json`, `cases/lint-scoped.stored.json`, ...), decoded. */
export const fixtureDoc = (name: string): RequirementsDocument =>
  decodeDoc(JSON.parse(fixtureText(name)))

/** One op stream (`cases/<case>.ops.jsonl`), decoded; `#` lines are comments. */
export const fixtureOps = (name: string): readonly DocumentOp[] =>
  fixtureText(name)
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.length > 0 && !l.startsWith('#'))
    .map((l) => Effect.runSync(decodeOp(JSON.parse(l))))

/** The fixture's requirement ids by key. */
export const ID = {
  'CAB-R1': '5a1e0000-0000-4000-8000-0000000000c1',
  'CAB-R2': '5a1e0000-0000-4000-8000-0000000000c2',
  'LOG-R1': '5a1e0000-0000-4000-8000-0000000000a1',
  'LOG-R2': '5a1e0000-0000-4000-8000-0000000000a2',
  'ORD-R1': '5a1e0000-0000-4000-8000-0000000000b1',
  'ORD-R2': '5a1e0000-0000-4000-8000-0000000000b2',
  'TNK-R1': '5a1e0000-0000-4000-8000-0000000000d1',
  'TNK-R2': '5a1e0000-0000-4000-8000-0000000000d2',
  'CYC-A': '5a1e0000-0000-4000-8000-0000000000e1',
  'CYC-B': '5a1e0000-0000-4000-8000-0000000000e2',
} as const
export type FixtureKey = keyof typeof ID

/** The content hashes over `base.json`'s text, as the fold computes them (readings, fixture). */
export const HASH = {
  'LOG-R1': 'sha256:fd8b2c50a779708a19c161d83262563c7d8826c3f749072ab3eaf58b2c286ae0',
  'LOG-R2': 'sha256:c2bd1271a31955317e36a3ede3361500f1061ac287576762e1e60f4d7227e42a',
  'LOG-R1,LOG-R2': 'sha256:716cbd99ed8163a6c487418cfc3b0b147668af2cb9e4a4c353689723e80cb733',
  'CAB-R1,CAB-R2': 'sha256:7092d13706b6f9b5b8c407fe8fa96a6d50603b68e6749122534d5e5fb1c08817',
  'ORD-R1': 'sha256:e376ee5c3ca6dfa2b6aab589e457c1a3c818dcbaffa9401002cc761478ba15b1',
  'ORD-R2': 'sha256:447120f0804d769c9c5e1c0b473058543e1cc9dcbf30776a0d6f16b5956067e3',
  'ORD-R1,ORD-R2': 'sha256:743432fc769be93bf7293a2c26d788d48cf18b44e5970eee0c671df5d45eb21d',
  /** LOG-R1 after it reads "store an audit record with the shift id" (lint-stale-hash). */
  'LOG-R1 edited': 'sha256:37bcc820ebf8449926122dbf1a332ef2fa447430682d0e384118a4a2589411b0',
  'CYC-A,CYC-B': 'sha256:b889a619770dd3929dc8c4d4086a52eece775a3995d5da76d61c43ffa8191524',
} as const

/** Ids of `keys`, sorted as the fold stores an exact set. */
export const ids = (...keys: readonly FixtureKey[]): readonly string[] =>
  keys.map((k) => ID[k]).sort()

/** The hash the fold would compute over `keys` in `doc` now. */
export const hashOf = (doc: RequirementsDocument, ...keys: readonly FixtureKey[]): string => {
  const h = requirementsContentHash(doc, [...ids(...keys)])
  if (h === undefined) throw new Error(`no hash over ${keys.join(', ')}`)
  return h
}

/** The fixture's near pairs for the semantic tier (`embedder.json`). */
export const NEAR: readonly (readonly [string, string])[] = (
  JSON.parse(fixtureText('embedder.json')) as { near: [string, string][] }
).near

/**
 * `document` with `waivers` written straight into its stored JSON — no fold, no fence. The
 * hand-edit channel a check-time twin must hold (trust boundary TB3, risk R4).
 */
export const withRawWaivers = (
  document: RequirementsDocument,
  waivers: readonly Readonly<Record<string, unknown>>[],
): RequirementsDocument => ({
  ...document,
  waivers: [...document.waivers, ...(waivers as unknown as RequirementsDocument['waivers'])],
})

/** `document` with its waiver at `index` deleted (the S3-016 and S3-023 counterfactual). */
export const withoutWaiver = (
  document: RequirementsDocument,
  index: number,
): RequirementsDocument => ({
  ...document,
  waivers: document.waivers.filter((_, i) => i !== index),
})

/** The real `check` and solver, handed in by the test file (ring rule). */
export interface CheckWiring {
  readonly check: (
    input: Readonly<Record<string, unknown>>,
  ) => Effect.Effect<
    { readonly exit: number; readonly data: unknown },
    unknown,
    DocStore | DocPath | EmbedderService | SolverService
  >
  readonly solver: Layer.Layer<SolverService>
}

/** One `check` run: its exit code and its payload, read loosely so new fields can be asserted. */
export interface CheckRun {
  readonly exit: number
  readonly data: CheckData
}

/** A finding as the payload carries it. */
export interface FindingView {
  readonly code: string
  readonly severity: string
  readonly requirementIds: readonly string[]
  readonly message?: string
  readonly suggestion?: string
  readonly [k: string]: unknown
}

/** A demotion as the payload carries it. */
export interface DemotionView {
  readonly reason: string
  readonly requirementIds: readonly string[]
  readonly action?: string
  readonly repair?: { readonly ops?: readonly Readonly<Record<string, unknown>>[] }
  readonly [k: string]: unknown
}

/** A `data.diagnostics` entry, with the S3 `waiver-inert` fields read loosely. */
export interface DiagnosticView {
  readonly kind: string
  readonly severity: string
  readonly detail: string
  readonly requirementIds?: readonly string[]
  /** S3: the stored waiver this diagnostic is about, as stored. */
  readonly waiver?: Readonly<Record<string, unknown>>
  /** S3: the replacement ops (`unwaive` first, then any scoped `waive`). */
  readonly ops?: readonly Readonly<Record<string, unknown>>[]
  readonly [k: string]: unknown
}

/** An S3 `data.ignoredWaivers` entry (a stale-hash waiver). */
export interface IgnoredWaiverView {
  readonly code: string
  readonly requirementIds: readonly string[]
  readonly storedHash: string
  readonly currentHash: string
  readonly reason?: string
  readonly note?: string
  readonly ops?: readonly Readonly<Record<string, unknown>>[]
  readonly [k: string]: unknown
}

/** An S3 `data.appliedWaivers` entry: a waiver the engine applied. */
export interface AppliedWaiverView {
  readonly code: string
  readonly requirementIds: readonly string[]
  readonly reason: string
  readonly [k: string]: unknown
}

/** The `check` payload, with the fields S3 adds as optional (absent on base). */
export interface CheckData {
  readonly verified: boolean
  readonly waived: number
  readonly findings: readonly FindingView[]
  readonly coverage: { readonly demotions: readonly DemotionView[] }
  readonly diagnostics: readonly DiagnosticView[]
  readonly ignoredWaivers?: readonly IgnoredWaiverView[]
  readonly appliedWaivers?: readonly AppliedWaiverView[]
  readonly [k: string]: unknown
}

/**
 * Run `check` on `document` in process, with the fixture embedder (or `near` pairs given).
 * `input` adds check options (`strict`, `minSeverity`, `codes`, ...).
 */
export const checkDocument = async (
  wiring: CheckWiring,
  document: RequirementsDocument,
  input: Readonly<Record<string, unknown>> = {},
  near: readonly (readonly [string, string])[] = NEAR,
): Promise<CheckRun> => {
  const store = Layer.succeed(DocStore)(
    documentOnlyStore({
      load: (path) =>
        path === 'doc.json'
          ? Effect.succeed({ document, unknownKeys: {}, diagnostics: [] })
          : Effect.fail(new ErrDocNotFound({ error: `no document at ${path}`, suggestions: [] })),
      save: () => Effect.void,
      exists: () => Effect.succeed(true),
    }),
  )
  const runtime = ManagedRuntime.make(wiring.solver)
  try {
    const run = await runtime.runPromise(
      wiring
        .check({ file: 'doc.json', ...input })
        .pipe(
          Effect.provide(
            Layer.mergeAll(
              store,
              Layer.succeed(DocPath)(makeDocPath({})),
              embedderLayerOf(orthogonalEmbedder(near)),
            ),
          ),
        ),
    )
    return { exit: run.exit, data: run.data as CheckData }
  } finally {
    await runtime.dispose()
  }
}

/** Requirement ids of a finding or demotion, read as fixture keys, sorted. */
export const keysOf = (
  document: RequirementsDocument,
  requirementIds: readonly string[],
): readonly string[] => requirementIds.map((id) => document.requirements[id]?.key ?? id).sort()

/** `reason [keys]` for every demotion, sorted: the shape the readings state demotions in. */
export const demotionRows = (document: RequirementsDocument, run: CheckRun): readonly string[] =>
  run.data.coverage.demotions
    .map((d) => `${d.reason} [${keysOf(document, d.requirementIds).join(', ')}]`)
    .sort()

/** `code [keys]` for every finding, sorted. */
export const findingRows = (document: RequirementsDocument, run: CheckRun): readonly string[] =>
  run.data.findings
    .map((f) => `${f.code} [${keysOf(document, f.requirementIds).join(', ')}]`)
    .sort()

/** The `waiver-inert` diagnostics of a run. */
export const inertDiagnostics = (run: CheckRun): readonly DiagnosticView[] =>
  run.data.diagnostics.filter((d) => d.kind === 'waiver-inert')
